name: "💬 Feedback / Report"
description: "Submit a bug, request a feature, or provide general feedback for Being Infinity Codify"
title: "[Feedback] "
labels: feedback
body:
  - type: dropdown
    id: feedback_type
    attributes:
      label: "Type"
      description: "Select the type of feedback"
      options:
        - "🐛 Bug"
        - "✨ Feature"
        - "💡 Other"
    validations:
      required: true

  - type: input
    id: feedback_title
    attributes:
      label: "Short Title"
      description: "Provide a concise title for your feedback"
      placeholder: "Example: Login button not working"
    validations:
      required: true

  - type: textarea
    id: feedback_description
    attributes:
      label: "Description"
      description: "Describe the feedback in detail"
      placeholder: "Steps to reproduce, expected behavior, etc."
    validations:
      required: true

  - type: input
    id: contact_email
    attributes:
      label: "Contact Email"
      description: "We may reach out for clarification"
      placeholder: "you@example.com"
